server:
  port: 8081
#  port: ${PORT:${SERVER_PORT:0}}

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microservicios
    username: jckballero
    password: Abcd1234
    driver: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  application:
    name: USUARIO-SERVICE

eureka:
  instance:
    prefer-ip-address: true
#    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    fetch-register: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka